integration_tests/suite/test_configs.py
provd/app.py
provd/persist/common.py
provd/persist/util.py
provd/rest/api/api.yml
provd/rest/server/server.py

It was possible to delete configurations that had the deletable field
set to False. This created problems when someone deleted the base
configuration by accident and could not get it back.

config: do not allow deletion of non-deletable configurations

---

debian/wazo-provd.service

reason: to see the daemon name in the journalctl/syslog instead of
`twistd`

debian: add SyslogIdentifier on service file

---

debian/wazo-dhcpd-update.cron.d

Running the DHCP server is optional and should not send a mail to the
administrator.

dhcpd-update cron: avoid failling when dhcp is disabled

---

provd/rest/server/helpers/tenants.py

Depends-on: https://github.com/wazo-platform/xivo-lib-python/pull/45

remove legacy from_headers_one helper

---

etc/wazo-provd/config.yml
integration_tests/assets/etc/wazo-provd/config.yml
provd/config.py

Depends-on: https://github.com/wazo-platform/xivo-test-helpers/pull/31
Jira-Issue: https://wazo-dev.atlassian.net/browse/WAZO-1689
Jira-Issue: https://wazo-dev.atlassian.net/browse/WAZO-1689

use auth without ssl by default

---

provd/rest/api/api.yml

reason: over complicated to hack the file with twisted to dynamically
change the basePath and schemes. It will avoid to mix nginx logic with
daemon.

hardcode basePath in openapi spec

---

integration_tests/suite/test_devices.py

Why:
* Acting on an unauthorized tenant should raise 401 error
* Acting on objects belonging to another visible but out-of-scope
tenant returns 404 and is already tested
Depends-On: https://github.com/wazo-platform/xivo-test-helpers/pull/41

tenant tests: fix status code assertion

---

provd/rest/api/api.yml

- Adds `PUT` requests api reference for the following routes :
* `/configure/plugin_server`
* `/configure/http_proxy`
* `/configure/https_proxy`
* `/configure/ftp_proxy`
* `/configure/locale`
* `/configure/NAT`

[WAZO-2477] Add api reference for /configure/ routes

---

provd/rest/server/server.py

Why: impossible to debug when a JSON field is missing in config otherwise

devices: add logger for unknown error on PUT

---

provd/rest/server/auth.py
provd/servers/http_site.py

is_valid now returns True or raises an exception
Depends-On: https://github.com/wazo-platform/wazo-auth-client/pull/28
Depends-On: https://github.com/wazo-platform/xivo-lib-python/pull/96

auth verifier: adapt to the new interface of the auth client

---

debian/control

why: wazo-dhcpd-update doesn't depends from provd code

debian: remove provd from pre-depends for dhcpd-update

---

Dockerfile
requirements.txt
tox.ini

How:
* Twisted seems to download the latest version of the lib "incremental"
by itself, without regards for the constraints in requirements.txt.
* When installing typing from requirements.txt, Twisted loads "incremental"
before typing is even installed by pip

docker: fix building image

---

requirements.txt

why: twisted require unpinned automat version and this library has
released a new version (22.10.0) which is incompatible with python2
That's why we pin automat to buster version

pin automat dependency to support python2

---

integration_tests/suite/test_devices.py
provd/persist/util.py

Explanation: Python 3 is more strict on comparisons than Python 2, so it raised an exception when a key was not present in a device JSON. For example, if we tried to sort the devices by ip but one of the devices did not have the key:value at all, there would be the following exception:
"TypeError: '<' not supported between instances of 'NoneType' and 'str'"

devices: fix devices list when a key is missing

---

README.md
provd/persist/tests/test_persist.py
provd/persist/util.py
requirements.txt

1. sorting error
`builtins.TypeError: '<' not supported between instances of 'int' and 'str'`
Appears when the field is an integer and not a string.
2. twisted has been updated to 19.7.0, due to error when executing unit tests:
```
Could not find a version that satisfies the requirement twisted==18.9.0 (from versions: 19.7.0, 19.10.0, 20.3.0, 21.2.0rc1, 21.2.0, 21.7.0rc1, 21.7.0rc2, 21.7.0rc3, 21.7.0, 22.1.0rc1, 22.1.0, 22.2.0rc1, 22.2.0, 22.4.0rc1, 22.4.0, 22.8.0rc1, 22.8.0, 22.10.0rc1, 22.10.0)
ERROR: No matching distribution found for twisted==18.9.0
```

Fix sorting issue

---

contribs/tzdataexport.py

* migrated to python 3 in WAZO-2819-migrate-to-python-3.7
Since only usage found for this script was in provd, it was decided to migrate it.
* Adjusted so that "SAVE" field processing accepts negative values(necessary to work with the test inputs)
* tested with input from https://data.iana.org/time-zones/releases/tzdata2022g.tar.gz
* is there an easy way to validate the output? there is an output example (https://github.com/wazo-platform/wazo-provd/blob/master/provd/tzinform/tzdatax) but no matching input.
* I assume we want to add some documentation somewhere about this? README.md?
* if we overwrite /provd/tzinform/tzdatax with a new version(using the recent database above), what is the impact?
* automatically run in CI to have up-to-date timezone configs?

importing contribs/tzdataexport.py from xivo-utils

---

etc/wazo-provd/config.yml

Why:
* Now that nginx is used to reverse-proxy requests to wazo-provd, we
need to trust the IP address of the request to nginx in order to
detect the IP address of the phone

config: use num_http_proxies = 1

---

etc/wazo-provd/config.yml
integration_tests/assets/etc/wazo-provd/config.yml
provd/config.py
provd/main.py

Why: when using a reverse proxy it is useless to listen to anything other than 127.0.0.1

http: add listen_interface

---

debian/changelog
debian/wazo-provd.dirs
debian/wazo-provd.install
debian/wazo-provd.links
etc/wazo-provd/config.yml
provd/config.py
provd/main.py

Why: internal (provd-nginx) port and external (from nginx) ports
are not the same but the phones need to know the second (from nginx) port
because it's the one that is exposed.
The public port (http_port in the configuration) is used by phones for their provisioning URL. It should thus not be the private port.
It is necessary to revert the changes to both provd and the database to be able to provision phones correctly. Also, removing the nginx reverse proxy for now is the solution.
See [xivo-manage-db](https://github.com/wazo-platform/xivo-manage-db/pull/228) for the database correction.
See [xivo-config](https://github.com/wazo-platform/xivo-config/pull/90) for the configuration correction.

[WAZO-3420] config: revert changes to HTTP ports

---

provd/config.py

Why:
* When base_external_url is not set, all phones will use localhost:8667
for fetching secondary files linked from primary files, which is invalid

config: fix default value for base_external_url

---

CHANGELOG.md
etc/wazo-provd/config.yml
provd/app.py
provd/config.py
provd/devices/config.py

why: previous logic was a wrong refactor that break the base_raw_config
logic by overriding base_raw_config with app_raw_config. But we want to
override app_raw_config with base_raw_config
why: this option doesn't modify anymore the listening port
why: is was redundant with advertised_http_url

Pull request for WAZO-3502-simplify-provd-config

---

provd/devices/schemas.py
provd/devices/tests/test_config.py

Why: it does not make sense to make it mandatory everywhere. It can be
defined in a template that is inherited by children that don't need to
redefine it.

schemas: remove mandatory http_port and tftp_port validators

---

integration_tests/Makefile
integration_tests/assets/docker-compose.yml
integration_tests/docker/Dockerfile-http-server
wazo_provd/devices/ident.py
wazo_provd/devices/tests/test_ident.py

Why:
* It returns an error 500 instead of a more standard error
* It can make wazo-provd crash, see WAZO-3686

WAZO-3691 http: handle error when GET /$key with no file

---

wazo_provd/app.py
wazo_provd/rest/server/helpers/tenants.py
zuul.yaml

why: get has been removed to make query lazy (when properties are
fetched)
Depends-on: https://github.com/wazo-platform/xivo-lib-python/pull/137

WP-1476 tenant helpers: update logic to reflect upstream

---

Dockerfile

Why:
* Latest version of incremental is downloaded by twisted at install
time
* Latest version of incremental is incompatible with setuptools 58

Dockerfile: pin version of twisted dependency

---

Dockerfile

why: to avoid to copy other unrelated directories (ex: build, .*)

dockerfile: avoid to copy entire repo to docker

---

usr/bin/dhcpd-update

How:
* If proxies={}, urllib (and requests) will ignore any *_PROXY variable
* If proxies=None (default), the *_PROXY variables will be respected

dhcpd-update: fix proxy env variables

---

wazo_provd/tests/test_tzinform.py
wazo_provd/tzinform.py

Also, change format used for timezone definition like it was before: `Wx.x` (`month week number (1-5)`.`week day (1-7, 1 = Monday)`)

tzinform: handle when no dst/std in zone information
